format = '$fill[* * *   $status   * * *](dimmed white)$fill$line_break $all$fill$jobs$cmd_duration$time$line_break $battery$username$hostname$hostip$container$shell$character'

[fill]
symbol = ' '
style = 'dimmed white'

[battery]
format = '[ $symbol $percentage ]($style)'
full_symbol = 'ó°¹ '
charging_symbol = 'ó°‚„ '
discharging_symbol = 'ó°¿ '
unknown_symbol = 'ó°‚‘ '
empty_symbol = 'ó°‚Ž '

[[battery.display]]
threshold = 95
style = 'green'

[[battery.display]]
threshold = 40
style = 'yellow'

[[battery.display]]
threshold = 15
style = 'red'

[cmd_duration]
min_time = 5000
format = '[ ï‰’ $duration ]($style)'
style = 'inverted yellow'

[directory]
truncation_length = 0
truncation_symbol = 'â€¦/'
read_only = ' ó°¯ '

[directory.substitutions]
'/boot' = '/ðŸ¥¾'
'/lib' = '/ðŸ“š'
'/log' = '/ðŸªµ'
'/run' = '/ðŸƒ'
'/Documents' = '/ó±”—'
'/Downloads' = '/ï€™'
'/Music' = '/ó°ˆ£'
'/Pictures' = '/ï‡…'
'/.config' = '/âš™'

[status]
disabled = false
format = '[$symbol]($style)'
style = 'dimmed white'
symbol = '[â€¼](dimmed yellow)'
success_symbol = '[âœ“](dimmed green)'
not_executable_symbol = '[Ã—](dimmed red)'
not_found_symbol = '[â¬š](dimmed blue)'
sigint_symbol = '[â•Ž](dimmed purple)'
signal_symbol = '[â€ ](dimmed white)'
recognize_signal_code = true
map_symbol = true
pipestatus = true
pipestatus_format = '[$pipestatus => $symbol]($style)'
pipestatus_separator = '[ | ](dimmed white)'

[sudo]
disabled = false

[time]
disabled = false
format = '[ ï€— $time ]($style)'
style = 'inverted blue'
